### ISSUE TITLE
cudnn not found in 32.2-jax-jetpack-4.2.1-runtime	

### ISSUE THREAD

**Issue by shubjain26** [idavis/jetson-containers#25]
Image size : 1.23 Gb
Image Name : l4t:32.2-jax-jetpack-4.2.1-runtime

Unable to find Cudnn in  _32.2-jax-jetpack-4.2.1-runtime_

But it is present in _32.2-tx2-jetpack-4.2.1-runtime_, so is this expected or a bug?

**Comment by idavis** [comment]
Hi @shubjain26, cuDNN is installed in the dev container image but not the runtime container image. You can look at its [dockerfile](https://github.com/idavis/jetson-containers/blob/102a2f4116471df14dc8dc74699add28bc3a3d3d/docker/jetpack/4.2.1/jax/devel/Dockerfile#L31-L34) to see how to install libcudnn.

**Comment by idavis** [comment]
Closing issue due to no response.
