### ISSUE TITLE
Installing Kubernetes on rootfs

### ISSUE THREAD

**Issue by eliabruni** [idavis/jetson-containers#29]
Hi @idavis,

I would like to install a single-node Kubernetes on a custom jetson rootfs. What I would like to obtain is a [k3s](https://k3s.io/) single cluster where I can have multiple jetson docker images talking to each other.

I am following [this guide](https://medium.com/jit-team/building-a-gpu-enabled-kubernets-cluster-for-machine-learning-with-nvidia-jetson-nano-7b67de74172a) (see "Configuring the base system"). The problem I am encountering is that, to have gpu support, I would have to move from `runc` to `nvidia-docker2` as default runtime (https://github.com/NVIDIA/nvidia-docker/wiki/Advanced-topics). This is annoying because, as far as I can see, it means building a very heavy rootfs image, with lots of devel-like image deps in order to have nvidia-docker2 installed (btw, do current jetpack devel images have nvidia-docker2 installed?).

What do you think? Is there something I'm missing?

**Comment by idavis** [comment]
If using the nvidia-docker2 runtime, you can use images from [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base). When you flash a device with the SDK manager for 4.2.1, 4.2.2, and 4.3, it will automatically install the nvidia-docker2 runtime in the host OS. The r32.2, r32.2.1, and r32.3.1 are ~410MB. 

Here is where the philosophical difference between jetson-containers and nvidia-docker2 come in.

When you use the SDK Manager and use the nvidia-docker2 runtime, you also install four csv files: cuda.csv, tensorrt.csv, cudnn.csv, and visionworks.csv. When you start a container with nvidia-docker2, it looks at those four files and mounts every file in them from the host OS into the container. This means you must have these components in the host OS and you must figure out how to update the host OS if you ever need to update these components.

This is in direct contrast to jetson-containers which only requires the BSP on the host OS, and pushes everything else into containers where everything is controlled via OCI images.

So you are correct, using nvidia-docker2 requires a very heavy rootfs, and small containers. Using jetson-containers requires small rootfs, and heavier containers. I say heavier as the base images are ~465MB-475MB compared to the ~410MB NGC bases. Everything above that is added for just what dependencies you need.

You don't need to run nvidia-docker2 to get GPU acceleration on Jetson devices.

**Comment by eliabruni** [comment]
Thanks for the prompt response @idavis!

I understand the philosophical difference between nvidia-docker2 and jetson-containers, thanks for reviewing it, and am definitely marrying the latter, which I find clearly more convenient for a production-like environment. 

I think that my doubts boil down to how to have GPU acceleration on Jetson devices in Kubernetes. I know I can run a single container with GPU enabled, but I am not sure how to setup it up in Kubernetes. I'll search that:)

**Comment by idavis** [comment]
@eliabruni CRIO supports `--additional-devices`, docker-compose supports `devices:`,  but I'm not sure about k3s and I think k8s general device support is pretty poor. That being said, this isn't something I've looked at yet. You have have to run the container privileged unless you can figure out the CAPS to add and volumes to mount. It is odd to me that k3s pitches itself for IoT but doesn't let you access the hardware.

**Comment by eliabruni** [comment]
Ah nice, I didn't know about CRI-O. It is also documented in [KUBERNETES ON NVIDIA GPUS](https://docs.nvidia.com/datacenter/pdf/kubernetes-install-guide.pdf). I'll move to CRI-O then.

It is indeed odd that k3s doesn't let access the hardware. I found a [Kubernetes Device Plugin by Google](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu) that is supposed to run on GCE (no nvidia-docker2), but it seems a riskier/more unstable path.

**Comment by idavis** [comment]
I would have to check, but I think the k8s on nvidia is based on https://github.com/NVIDIA/k8s-device-plugin - which could be ported to jetson I would expect.

**Comment by eliabruni** [comment]
That's indeed the first plugin I found. According to [here](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/), it requires nvidia-docker2 and that's where I found the nvidia-docker2-free plugin. Porting k8s to Jetson would be very nice and I guess next natural step in jetson-containers philosophy.
