### ISSUE TITLE
recipe failure when building the rootfs flashing image

### ISSUE THREAD

**Issue by eliabruni** [idavis/jetson-containers#36]
HI @idavis ,

Probably this is not a supported feature yet, but I'll report it anyway in case it helps.

When running:

```
make image-32.3.1-jax-dev-jetpack-4.3
```

I get:

```
...
Makefile:56: recipe for target 'image-32.3.1-jax-dev-jetpack-4.3' failed
make: *** [image-32.3.1-jax-dev-jetpack-4.3] Error 2
```

**Comment by idavis** [comment]
What is `jax-dev`? The `nano` has an additional `nano-dev` as they are really different devices with the `nano` being the production module whereas the `nano-dev` is missing the `eMMC` for flashing.

**Comment by eliabruni** [comment]
Ups, sorry, I forgot to remove `-dev`, now it works fine!
