### ISSUE TITLE
jetson-containers philosophy 

### ISSUE THREAD

**Issue by eliabruni** [idavis/jetson-containers#38]
HI @idavis,

Here comes a philosophical question.

I am working on a robot app which is running on a jetson Xavier. This application will have several modules such as a vision system, motion control, navigation, etc. In principle, all modules could run some machine learning and therefore would have (*common*) dependencies such as Cuda. 

I would like to have the application containerized and implement best CI/CD practices and am thinking about the following options:

1. A single Docker image with all my application in it. 
PROS: This would be very easy to implement, and I could follow the jetson-containers pattern right away.
CONS: Having a single, heavy image doesn't sound very smart.

2. A Docker image per module and image orchestration via Kubernetes (e.g., k3s).
PROS: Easier to maintain; fault tolerance wrt specific modules; migrations become easier; etc.
CONS: It is not 100% clear to me how should I approach the jetson-containers pattern. 

A potential solution I envision for option 2 is to (i) create my custom rootfs; (ii) on top of it run a base docker image which has Kubernetes installed; (iii) docker-in-docker style, run all my modules from the base container. Of course, I could also skip the base and have only (i) and (iii).

If the solution above makes sense (please, let me know if you'd have a better way!), then I see a problem: Let's say the robot app is made of 10 modules and that all these modules have Cuda as a dependency. To follow jetson-containers best practices, should I have 10 heavy docker images with the redundant Cuda dependency in it?  Wouldn't make sense instead to install Cuda together with nvidia-docker2 runtime into the base, and then leverage from it in all modules? Plus, having nvidia-docker2 runtime would also allow to easily run the Kubernetes Device Plugin (although that's not really a good argument).

Thanks.

**Comment by idavis** [comment]
There is a lot to unpack here. Please bear with me if I miss something.

Part 1

Docker layer caching ensures that if you have multiple containers that share layers that only one copy of the layers is pulled. Say you had 10 container images based on 32.3.1-jax-jetpack-4.3-all, the heaveist, only only copy of its layers would exist, but you would have 10 or more new layers which just have the additions you've made for your application. When building the base images I use `--squash` to remove extra files that were unavoidable as temporary files. And each image builds upon another image. Let's look at the nano-dev images:

```
l4t   32.3.1-nano-dev-jetpack-4.3-all             5.8GB
l4t   32.3.1-nano-dev-jetpack-4.3-devel-cudnn     4.26GB
l4t   32.3.1-nano-dev-jetpack-4.3-devel           3.37GB
l4t   32.3.1-nano-dev-jetpack-4.3-deepstream      3.37GB
l4t   32.3.1-nano-dev-jetpack-4.3-runtime-cudnn   1.88GB
l4t   32.3.1-nano-dev-jetpack-4.3-runtime         1.44GB
l4t   32.3.1-nano-dev-jetpack-4.3-base            683MB
```
if you pull `runtime` you'll get 1.44GB. If you then pull `base` nothing will be pulled and you'll see docker saying the layers exist already. Unless you are doing DeepStream, you will likely work your way down to `base` and then install the needed components. The other containers are really for convenience in getting started.

**Comment by eliabruni** [comment]
You're right, I didn't think about docker layer caching and how well the jetpack images are hierarchically organized!

Curious about the next Part...

**Comment by idavis** [comment]
Part 2

For anything speed sensitive, I recommend moving to as few containers as possible. The overhead of sending data between containers can cost dear milliseconds. Most of my work is with Azure IoT Edge and docker-compose. Azure IoT Edge handles the CD part.

With regards to fault tolerance, you can [specify the resiliency](https://docs.docker.com/config/containers/start-containers-automatically/) of your containers natively in docker. K3s and K8s won't give any additional fault tolerance as everything is running on a single node.

**Comment by idavis** [comment]
Part 3

I'm not sure about other tools, you can set up Azure DevOps with an environment (VM) which you can host in the cloud or on your machine. The [ARMing yourself](https://codepyre.com/2019/12/arming-yourself/) post would allow the `arm64v8` builds to take place on the VM.

Or, you could use it to run the builds on your Xavier device if you wish. Once you install QEMU on the host along with the arm32v7 part of [ARMing yourself](https://codepyre.com/2019/12/arming-yourself/), the arm build agent should work. (If setting up the VM, you are given a command to execute which includes `https://vstsagentpackage.azureedge.net/agent/2.164.7/vsts-agent-linux-x64-2.164.7.tar.gz`, just change `x64` to `arm`.

**Comment by eliabruni** [comment]
That's very useful feedback, @idavis , thank you!

@Part 2, I'll then try to follow your suggestions. I was already planning to use Azure IoT Edge, I will start right away. And freeze the k8s plan in favour of few containers coordinated with docker-compose.

@Part 3, my current plan is to try out Github Actions inside a VM or a container, and indeed run the builds on the Xavier. But I'll keep your suggestions in mind, in case I get stuck somewhere.
