### ISSUE TITLE
Problem with flashing rootfs

### ISSUE THREAD

**Issue by eliabruni** [idavis/jetson-containers#39]
Hi @idavis ,

I'm running into a problem which I find difficult to document. I have a Xavier (devel kit) and am trying to install a custom rootfs (jetpack 4.3). I follow all your instructions [here](https://codepyre.com/2019/08/building-root-filesystems-with-desktop-ui-support/) and am able to build the image successfully. Also the flashing works fine. I get then prompted to the UI configuration. However, after having configured the system, I reboot and it gets stuck in rebooting (it keeps bouncing between the terminal window and the NVIDIA desktop picture).  I tried the whole process several times, but with no success. I really do not know what's the problem. I will follow up with some pictures of the screen, maybe it is helpful.

**Comment by eliabruni** [comment]
![20200218_215552](https://user-images.githubusercontent.com/490453/74838077-2f417080-5323-11ea-9350-2f6cf022bdce.jpg)

**Comment by eliabruni** [comment]
![20200219_143444](https://user-images.githubusercontent.com/490453/74838234-89dacc80-5323-11ea-845f-f287f7d375e0.jpg)

**Comment by eliabruni** [comment]
In case it helps, here is also the log of image build:

```
make image-32.3.1-jax-jetpack-4.3
make -C jetson-containers/flash 32.3.1-jax-jetpack-4.3-image
make[1]: Entering directory 'jetson-containers/flash'
(DOCKER_BUILD_ROOT="jetson-containers/flash/l4t/32.3.1" etson-containers/flash/build.sh ./conf/32.3.1-jax-jetpack-4.3-image l4t:32.3.1-jax-jetpack-4.3-image)
Moving into jetson-containers/flash/l4t/32.3.1
jetson-containers/flash/l4t/32.3.1 jetson-containers/flash
docker build --squash -f jetson-containers/flash/l4t/32.3.1/default.Dockerfile -t l4t:32.3.1-jax-jetpack-4.3-image \
    --build-arg DEPENDENCIES_IMAGE=l4t:32.3.1-jax-jetpack-4.3-deps \
    --build-arg DRIVER_PACK=Jetson_Linux_R32.3.1_aarch64.tbz2 \
    --build-arg DRIVER_PACK_MD5=667462228a705bf3a64e83d0731c192a \
    --build-arg FS_DEPENDENCIES_IMAGE=l4t:ubuntu_bionic_desktop_aarch64-rootfs \
    --build-arg ROOT_FS=ubuntu_bionic_desktop_aarch64.tbz2 \
    --build-arg ROOT_FS_MD5=c923ab3f185769b04bb060be4024eda1 \
    --build-arg BSP_DEPENDENCIES_IMAGE= \
    --build-arg BSP= \
    --build-arg BSP_MD5= \
    --build-arg TARGET_BOARD=jetson-xavier \
    --build-arg ROOT_DEVICE=mmcblk0p1 \
    --build-arg VERSION_ID=bionic-20190912.1 \
    .
Sending build context to Docker daemon   29.7kB
Step 1/31 : ARG VERSION_ID
Step 2/31 : ARG DEPENDENCIES_IMAGE
Step 3/31 : ARG FS_DEPENDENCIES_IMAGE
Step 4/31 : FROM ${DEPENDENCIES_IMAGE} as dependencies
 ---> a84286916198
Step 5/31 : ARG VERSION_ID
 ---> Using cache
 ---> 2fcb74b78e6f
Step 6/31 : ARG FS_DEPENDENCIES_IMAGE
 ---> Using cache
 ---> 3b2711e15890
Step 7/31 : FROM ${FS_DEPENDENCIES_IMAGE} as fs-dependencies
 ---> e4c136b1cc4d
Step 8/31 : ARG VERSION_ID
 ---> Running in 8b7d62654072
Removing intermediate container 8b7d62654072
 ---> 5ca1b48ac699
Step 9/31 : FROM ubuntu:${VERSION_ID} as qemu
 ---> 2ca708c1c9cc
Step 10/31 : RUN apt-get update && apt-get install -y --no-install-recommends qemu-user-static &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 7c2f94a9a7ff
Step 11/31 : ARG VERSION_ID
 ---> Using cache
 ---> 8cbc7f9b452a
Step 12/31 : FROM ubuntu:${VERSION_ID}
 ---> 2ca708c1c9cc
Step 13/31 : COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64-static
 ---> Using cache
 ---> 35b4abfbd67a
Step 14/31 : RUN apt-get update && apt-get install -y --allow-downgrades     bzip2=1.0.6-8.1 libbz2-1.0=1.0.6-8.1     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 14fe47605b3e
Step 15/31 : RUN apt-get update && apt-get install -y     apt-utils     bzip2     curl     lbzip2     libpython-stdlib     perl     python     python-minimal     python2.7     python2.7-minimal     sudo     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> f0d09f5297cb
Step 16/31 : ARG DRIVER_PACK
 ---> Using cache
 ---> 60a6f091a6a8
Step 17/31 : ARG DRIVER_PACK_MD5
 ---> Using cache
 ---> f6d53eedd171
Step 18/31 : COPY --from=dependencies /data/${DRIVER_PACK} ${DRIVER_PACK}
 ---> Using cache
 ---> 9c22ee64096c
Step 19/31 : RUN echo "${DRIVER_PACK_MD5} *./${DRIVER_PACK}" | md5sum -c - &&     tar -xp --overwrite -f ./${DRIVER_PACK} &&     rm /${DRIVER_PACK}
 ---> Using cache
 ---> 4fb56b908003
Step 20/31 : ARG ROOT_FS
 ---> Using cache
 ---> bf189fd37d11
Step 21/31 : ARG ROOT_FS_MD5
 ---> Using cache
 ---> 8387798471d3
Step 22/31 : COPY --from=fs-dependencies /data/${ROOT_FS} ${ROOT_FS}
 ---> f0d976936819
Step 23/31 : RUN echo "${ROOT_FS_MD5} *./${ROOT_FS}" | md5sum -c - &&     cd /Linux_for_Tegra/rootfs &&     tar -xp --overwrite -f /${ROOT_FS} &&     rm /${ROOT_FS}
 ---> Running in 789eeae9084d
./ubuntu_bionic_desktop_aarch64.tbz2: OK
Removing intermediate container 789eeae9084d
 ---> 0282968b99e9
Step 24/31 : WORKDIR /Linux_for_Tegra
 ---> Running in d4e47729416d
Removing intermediate container d4e47729416d
 ---> 95588b109c5b
Step 25/31 : RUN ./apply_binaries.sh --target-overlay
 ---> Running in 91a1679623fe
Using rootfs directory of: /Linux_for_Tegra/rootfs
Extracting the NVIDIA user space components to /Linux_for_Tegra/rootfs
Extracting the BSP test tools to /Linux_for_Tegra/rootfs
Extracting the NVIDIA gst test applications to /Linux_for_Tegra/rootfs
Extracting Weston to /Linux_for_Tegra/rootfs
Extracting the configuration files for the supplied root filesystem to /Linux_for_Tegra/rootfs
Extracting graphics_demos to /Linux_for_Tegra/rootfs
Extracting the firmwares and kernel modules to /Linux_for_Tegra/rootfs
Extracting the kernel headers to /Linux_for_Tegra/rootfs/usr/src
Adding symlink /Linux_for_Tegra/rootfs/lib/modules/4.9.140-tegra/build --> /usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/kernel-4.9
Installing Image into /boot in target rootfs
Installing the board *.dtb and *.dtbo files into /boot in target rootfs
Rename ubuntu.desktop --> ux-ubuntu.desktop
Copying USB device mode filesystem image to /Linux_for_Tegra/rootfs
Disabling NetworkManager-wait-online.service
Disable the ondemand service by changing the runlevels to 'K'
Installing extlinux.conf into /boot/extlinux in target rootfs
Success!
Removing intermediate container 91a1679623fe
 ---> e37a5be34889
Step 26/31 : ARG TARGET_BOARD
 ---> Running in 9aafea9e9e32
Removing intermediate container 9aafea9e9e32
 ---> ace137e9d096
Step 27/31 : ARG ROOT_DEVICE
 ---> Running in 333aece3d68b
Removing intermediate container 333aece3d68b
 ---> ef679d9a4090
Step 28/31 : ENV TARGET_BOARD=$TARGET_BOARD
 ---> Running in a3d1fee9a857
Removing intermediate container a3d1fee9a857
 ---> c2076748db17
Step 29/31 : ENV ROOT_DEVICE=$ROOT_DEVICE
 ---> Running in 96e260bc3cd5
Removing intermediate container 96e260bc3cd5
 ---> 1e3333d13d65
Step 30/31 : RUN echo "#!/bin/bash" >> entrypoint.sh &&     echo "echo \"sudo ./flash.sh \$* ${TARGET_BOARD} ${ROOT_DEVICE}\"" >> entrypoint.sh &&     echo "sudo ./flash.sh \$* ${TARGET_BOARD} ${ROOT_DEVICE}" >> entrypoint.sh &&     chmod +x entrypoint.sh
 ---> Running in 29c10d43f914
Removing intermediate container 29c10d43f914
 ---> 5319e84f33e2
Step 31/31 : ENTRYPOINT ["sh", "-c", "sudo ./entrypoint.sh $*", "--"]
 ---> Running in d061b385c694
Removing intermediate container d061b385c694
 ---> 5232c5be7647
[Warning] One or more build-args [BSP BSP_DEPENDENCIES_IMAGE BSP_MD5] were not consumed
Successfully built 2cc92e373763
Successfully tagged l4t:32.3.1-jax-jetpack-4.3-image
```

**Comment by idavis** [comment]
@eliabruni I'll run through it again with the custom FS for xavier. I went through the standard jetpack sample os and it worked fine for 4.3.

**Comment by idavis** [comment]
@eliabruni  I found this missing in the 4.3 scripts from nvidia:
```
ln -sf "/opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode.service" "nv-l4t-usb-device-mode.service"
if [ -f "${LDK_ROOTFS_DIR}/opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.service" ]; then
	ln -sf "/opt/nvidia/l4t-bootloader-config/nv-l4t-bootloader-config.service" "nv-l4t-bootloader-config.service"
fi
```

I'm wondering if their --target-overlay flash option is broken. I'll try to get it working without overlay and see if that fixes the issue.

**Comment by idavis** [comment]
@eliabruni Currently: When I use overlay, the system is flashing and I can log in, but my network isn't working. When I use the debian packages, I get the loop that you are in.

**Comment by idavis** [comment]
@eliabruni I have the deb version flashing, but it boots into airplane mode and can't talk to the network. I need to dig into what is going on deeper in 4.3.

**Comment by eliabruni** [comment]
Hey @idavis , thanks for the prompt check!

I checked out the fix and ran the following:

```
jetson-containers$ sudo ./flash/flash.sh l4t:32.3.1-jax-jetpack-4.3-image
docker run --rm -it --privileged -v /dev/bus/usb:/dev/bus/usb l4t:32.3.1-jax-jetpack-4.3-image
root@e31b2222d46c:/Linux_for_Tegra# sudo ./flash.sh jetson-xavier mmcblk0p1
```

Assuming that's correct, the flash process reaches the end but then, on Xavier, I got stuck at (I tried with two different filesystems):

![20200220_153922](https://user-images.githubusercontent.com/490453/74944415-4d2bd580-53f6-11ea-94d0-92c0da51667d.jpg)

**Comment by idavis** [comment]
@eliabruni The hack doesn't fully work. Sorry that wasn't more clear. There is something more going on that I haven't been able to figure out yet due to time.

**Comment by eliabruni** [comment]
@idavis I see, no worries! I'll stay tuned then, thanks for looking into it.

**Comment by idavis** [comment]
I modified the minimal OS with UI, 
Ran `echo "deb http://ports.ubuntu.com/ubuntu-ports bionic universe" >> /etc/apt/sources.list` so that I could install `libgstreamer-plugins-bad1.0-0`

Then installed:
- `device-tree-compiler`
- `libunwind8`
- `python-minimal`
- `python2.7-minimal`

Once done I was able to flash with overlay and the system worked with the exception of an `etc/resolv.conf` issue which I think is from the unpacking/repacking. I'm doing it all again from scratch to verify. Then I'll need to test it without the UI as well. The apt packages they install have dependencies that are not part of a clean file system.

**Comment by eliabruni** [comment]
Thanks for the update! What kind of dependencies shouldn't be there? Are you planning to keep them out?

**Comment by idavis** [comment]
@eliabruni - I have it working, I need to push a change to the flashing dockerfile, and I need to update the blog posts with:

1.  `echo "deb http://ports.ubuntu.com/ubuntu-ports bionic universe" >> /etc/apt/sources.list`
2.  `apt update`
3. ` apt install python python3 -y --no-install-recommends`
Need to get 3,740 kB of archives.
After this operation, 16.3 MB of additional disk space will be used.
4.  `apt install device-tree-compiler libunwind8 libgstreamer-plugins-bad1.0-0 -y --no-install-recommends`
Need to get 4,467 kB of archives.
After this operation, 26.9 MB of additional disk space will be used.

Then you can continue with :
`apt install ubuntu-desktop oem-config-gtk -y --no-install-recommends`
Need to get 253 MB of archives.
After this operation, 1,061 MB of additional disk space will be used.

**Comment by idavis** [comment]
For unknown reasons it keeps booting into airplane mode...

**Comment by eliabruni** [comment]
Great to hear, @idavis ! Should I wait for your push before trying?

**Comment by idavis** [comment]
@eliabruni you can try the [branch I pushed](https://github.com/idavis/jetson-containers/tree/bugfix/4.3-flashing-rootfs) if you install the prerequisites I listed above.

**Comment by eliabruni** [comment]
Thanks, will do!

**Comment by idavis** [comment]
@eliabruni Any luck?

**Comment by idavis** [comment]
Closing as stale.
