### ISSUE TITLE
make all does not work

### ISSUE THREAD

**Issue by FluxReality** [idavis/jetson-containers#41]
`make all`

Returns:

`make: *** No rule to make target jetpack-deps, needed by all. Stop.`

I don't think this has worked since commit [97fda47dccb4e7afd75c814bc4d80777c6b321dd](https://github.com/idavis/jetson-containers/commit/97fda47dccb4e7afd75c814bc4d80777c6b321dd). Where **jetpack-deps** target was removed.

Also the README.md might be missleading on this topic:

> make jax-jetpack-4.2-deps, or make nano-dev-jetpack-4.2-deps, or make tx2-jetpack-4.2-deps, or make jetpack-4.2-deps to build them all

**Comment by idavis** [comment]
The `make all` command really shouldn't be used by most people. I use that kind of thing for testing to build out the platforms. I'll take a look at the readme shortly. Thank you for the feedback.

**Comment by FluxReality** [comment]
Thankyou @idavis for looking at this.

It was only after getting lost in the README.md documentation not working, that I started looking at the Makefile it self, to try and figure how to build these images. I got it working, sort of, but without understanding it enough to use it for production.

**Comment by idavis** [comment]
The blog post series is the best introduction I think. I'd start there. Let me know if anything else is giving you trouble.
