### ISSUE TITLE
Jetpack 4.4 support

### ISSUE THREAD

**Issue by ericvanbuhler** [idavis/jetson-containers#44]
Is there a plan to add Jetpack 4.4 support to the docker image build process?

Regards,
Eric

**Comment by idavis** [comment]
@ericvanbuhler Sorry I just saw this and other issues, somehow I didn't get a notification. I'll take a look. I have 4.3 patch to finish as NVIDIA broke the world with 4.3. Hopefully 4.4 is easier.

**Comment by idavis** [comment]
@ericvanbuhler see #45

**Comment by ericvanbuhler** [comment]
Thanks! I'll close the issue.
