### ISSUE TITLE
Question: Understanding different containers

### ISSUE THREAD

**Issue by oscarthorn** [idavis/jetson-containers#53]
Hi!

This is a great project! I'm trying to understand how everything is setup, so hoping you have time to confirm my understanding.

First the different containers:

Deps: These are just used for building other containers on a build machine.
Jetpack: These can be used a base images for application containers and contain jetpack SDKs.
Flashing: These are just for flashing and just contain the root filesystem.

Is this correct?

Also a second question. Am I understanding it correctly that this project does not use the nvidia-container runtime? And that instead cuda is included in the containers?

**Comment by idavis** [comment]
Deps: Yes, they are for snapshotting the dependencies needed to install. This changed a bit in 4.3 when NVIDIA introduced the apt sources. They are still needed for building the l4t base image as they have the OS and driver pack.

Jetpack: Yes, various pre-built jetpack subsets which you can use as a base or create your own from. I've worked hard to be able to minimize the container sizes. You can see this especially in the TensorFlow images.

Flashing: These are for creating reusable flashing containers. NVIDIA has just started following this same kind of pattern with the latest SDK Manager. Using these containers I can flash devices very quickly and not have to worry about files that may have changed on the host file system.

Correct, this project does not use the nvidia-container-runtime. The runtime mounts CUDA into the container to save space where there project includes everything.

**Comment by oscarthorn** [comment]
Thanks for clarifying!
