### ISSUE TITLE
Cross arch compilation support

### ISSUE THREAD

**Issue by direbearform** [idavis/jetson-containers#7]
Hi Ian, 

Firstly, I really love this project!

Maybe it is not that obvious to me but is it possible to build all the Jetson containers on x86 host instead of on the target device right now? I am asking as I'd love to leverage the CPU/Mem on host than Jetson SoCs (esp. nano).

The approach that I know is by injecting qemu emulator, and it worked great for me to build working containers.

I wonder if some how you can already pull this magic off that I don't see, or you'd love to integrate this feature? If the later, I am open to help with a PR too.

**Comment by idavis** [comment]
Hello @direbearform, I'm working on cross-compilation, just need to test. See [feature/host-cross-compilation](https://github.com/idavis/jetson-containers/tree/feature/host-cross-compilation).

**Comment by direbearform** [comment]
From my understanding your changes on that branch, it seems you are trying to build a container that contains the cross-compiling tool chains for building arm64 nv apps, is my understanding correct?

I was referring to the ability to build the arm64v8 jetson containers on the host (so that we don't need to run docker build on devices). Here is a prototype change here see if it makes sense?
https://github.com/direbearform/jetson-containers/commits/master

**Comment by idavis** [comment]
You are correct. I tried the path you suggest last year and hit some issues, but I'm happy to take another crack at it.

I think we need to change `RUN apt-get update && apt-get install -qqy qemu-user-static` to `RUN apt-get update && apt-get install -y --no-install-recommends qemu-user-static`. Other than that I think it looks correct.

Can you please submit a PR?

**Comment by direbearform** [comment]
Sure. Thank you!

**Comment by direbearform** [comment]
[PR created](https://github.com/idavis/jetson-containers/pull/8). I tested built tried on xubuntu 18.04 and Windows, both worked:
```
...
Successfully built 721fa4ed4852
Successfully tagged direbearform:32.1-jax-jetpack-4.2-devel
```
